# questions/knowledge.py
import random

def generate_aviation_info_questions():
    facts = [
        ("What controls an aircraft’s yaw?", ["rudder", "aileron", "elevator", "flaps", "throttle"], "rudder"),
        ("A high lift device on an aircraft is", ["flaps", "engine", "rudder", "propeller", "gear"], "flaps"),
        ("Runways are numbered based on", ["compass headings", "length", "altitude", "traffic", "location"], "compass headings"),
        ("The primary function of landing gear is", ["landing", "steering", "braking", "lifting", "cooling"], "landing"),
        ("What adjusts an aircraft’s pitch?", ["elevator", "rudder", "aileron", "flaps", "gear"], "elevator"),
        ("The altimeter measures", ["altitude", "speed", "direction", "temperature", "pressure"], "altitude"),
        ("Ailerons control an aircraft’s", ["roll", "pitch", "yaw", "lift", "speed"], "roll"),
        ("The force that opposes drag is", ["thrust", "lift", "gravity", "weight", "friction"], "thrust"),
        ("Lift is generated primarily by the", ["wings", "engine", "tail", "fuselage", "propeller"], "wings"),
        ("The cockpit is the location of the", ["pilot", "engine", "cargo", "passengers", "fuel"], "pilot"),
        ("What indicates airspeed?", ["airspeed indicator", "altimeter", "compass", "radar", "gauge"], "airspeed indicator"),
        ("The vertical stabilizer affects", ["yaw", "pitch", "roll", "speed", "lift"], "yaw"),
        ("Turbulence is caused by", ["air currents", "rain", "snow", "sunlight", "clouds"], "air currents"),
        ("The horizon line on an attitude indicator shows", ["pitch", "roll", "yaw", "speed", "altitude"], "pitch"),
        ("Jet engines produce thrust through", ["exhaust", "intake", "lift", "drag", "fuel"], "exhaust"),
        ("The rudder is located on the", ["tail", "wing", "nose", "fuselage", "gear"], "tail"),
        ("What measures direction in flight?", ["compass", "altimeter", "radar", "gauge", "speedometer"], "compass"),
        ("Stalls occur due to insufficient", ["lift", "thrust", "drag", "speed", "fuel"], "lift"),
        ("The empennage refers to the", ["tail", "wings", "nose", "engine", "gear"], "tail"),
        ("Flaps are used primarily during", ["takeoff", "cruise", "climb", "descent", "turn"], "takeoff"),
        ("The force that keeps an aircraft aloft is", ["lift", "thrust", "drag", "gravity", "weight"], "lift"),
        ("Airspeed is measured in", ["knots", "miles", "feet", "meters", "degrees"], "knots"),
        ("The yoke controls", ["pitch and roll", "yaw", "speed", "altitude", "thrust"], "pitch and roll"),
        ("What provides directional stability?", ["vertical stabilizer", "wings", "rudder", "flaps", "gear"], "vertical stabilizer"),
        ("Drag is a force that", ["slows", "lifts", "turns", "pushes", "climbs"], "slows"),
        ("The throttle controls", ["engine power", "pitch", "roll", "yaw", "brakes"], "engine power"),
        ("A headwind affects aircraft by", ["reducing groundspeed", "increasing lift", "raising altitude", "slowing thrust", "turning"], "reducing groundspeed"),
        ("The main purpose of ailerons is to", ["bank", "climb", "descend", "yaw", "brake"], "bank"),
        ("What is the primary flight control surface for turning?", ["aileron", "rudder", "elevator", "flaps", "gear"], "aileron"),
        ("The angle of attack affects", ["lift", "speed", "drag", "thrust", "roll"], "lift"),
        ("Propellers are most common on", ["piston aircraft", "jets", "helicopters", "gliders", "rockets"], "piston aircraft"),
        ("The fuselage houses the", ["cockpit", "wings", "tail", "engine", "gear"], "cockpit"),
        ("What indicates an aircraft’s heading?", ["compass", "altimeter", "radar", "speedometer", "gauge"], "compass"),
        ("The primary purpose of the elevator is to", ["change pitch", "roll", "yaw", "speed", "lift"], "change pitch"),
        ("Wingtip vortices cause", ["turbulence", "lift", "thrust", "drag", "speed"], "turbulence"),
        ("A crosswind affects", ["takeoff", "cruise", "climb", "descent", "speed"], "takeoff"),
        ("The trim adjusts", ["control surfaces", "speed", "altitude", "thrust", "drag"], "control surfaces"),
        ("What measures atmospheric pressure?", ["altimeter", "compass", "radar", "gauge", "speedometer"], "altimeter"),
        ("The pitot tube measures", ["airspeed", "altitude", "direction", "temperature", "fuel"], "airspeed"),
        ("The primary role of the horizontal stabilizer is", ["pitch stability", "roll", "yaw", "speed", "lift"], "pitch stability"),
        ("A tailwind increases", ["groundspeed", "airspeed", "lift", "drag", "altitude"], "groundspeed"),
        ("What is used to reduce drag on modern aircraft?", ["streamlining", "flaps", "gear", "rudder", "propeller"], "streamlining"),
        ("The primary purpose of spoilers is to", ["reduce lift", "increase lift", "turn", "climb", "speed"], "reduce lift"),
        ("A jet’s thrust comes from", ["exhaust gases", "propellers", "wings", "tail", "gear"], "exhaust gases"),
        ("The angle of incidence is between the wing and", ["fuselage", "tail", "ground", "airflow", "rudder"], "fuselage"),
        ("What prevents ice buildup on wings?", ["de-icing system", "flaps", "ailerons", "rudder", "gear"], "de-icing system"),
        ("The turn coordinator indicates", ["rate of turn", "altitude", "speed", "pitch", "lift"], "rate of turn"),
        ("What provides lift in a helicopter?", ["rotor blades", "tail", "engine", "fuselage", "gear"], "rotor blades"),
        ("The primary purpose of the landing gear brakes is", ["stopping", "steering", "lifting", "cooling", "turning"], "stopping"),
        ("What indicates an aircraft’s rate of climb?", ["vertical speed indicator", "altimeter", "compass", "radar", "gauge"], "vertical speed indicator")
    ]
    random.shuffle(facts)
    questions = [f"{q}\nOptions: {', '.join(opts)}" for q, opts, _ in facts]
    answers = [ans for _, _, ans in facts]
    return questions[:20], answers[:20], None

def generate_general_science_questions():
    facts = [
        ("An element is defined by its number of", ["protons", "electrons", "neutrons", "atoms", "ions"], "protons"),
        ("The primary source of Earth’s energy is", ["sun", "moon", "wind", "core", "ocean"], "sun"),
        ("Water turns to vapor through", ["evaporation", "condensation", "freezing", "melting", "sublimation"], "evaporation"),
        ("A metal typically conducts", ["electricity", "sound", "light", "heat", "cold"], "electricity"),
        ("The Earth’s atmosphere is mostly", ["nitrogen", "oxygen", "carbon dioxide", "helium", "hydrogen"], "nitrogen"),
        ("Gravity is a force that", ["attracts", "repels", "spins", "lifts", "stops"], "attracts"),
        ("Photosynthesis produces", ["oxygen", "carbon dioxide", "nitrogen", "hydrogen", "helium"], "oxygen"),
        ("The freezing point of water in Celsius is", ["0", "32", "100", "-273", "50"], "0"),
        ("A mammal is characterized by having", ["hair", "scales", "feathers", "gills", "claws"], "hair"),
        ("The speed of sound is fastest in", ["solids", "liquids", "gases", "vacuum", "air"], "solids"),
        ("An acid turns litmus paper", ["red", "blue", "green", "yellow", "white"], "red"),
        ("The primary gas in Earth’s core is", ["none", "oxygen", "nitrogen", "hydrogen", "helium"], "none"),
        ("The boiling point of water in Celsius is", ["100", "0", "32", "212", "50"], "100"),
        ("A lever is an example of a", ["simple machine", "compound", "element", "force", "liquid"], "simple machine"),
        ("The smallest unit of an element is an", ["atom", "molecule", "cell", "ion", "proton"], "atom"),
        ("Light travels fastest in a", ["vacuum", "water", "glass", "air", "metal"], "vacuum"),
        ("The primary source of tides is the", ["moon", "sun", "wind", "earth", "stars"], "moon"),
        ("A plant’s green color comes from", ["chlorophyll", "sugar", "water", "soil", "roots"], "chlorophyll"),
        ("The hardest natural substance is", ["diamond", "iron", "gold", "quartz", "steel"], "diamond"),
        ("Electricity flows easily through a", ["conductor", "insulator", "gas", "liquid", "vacuum"], "conductor"),
        ("The Earth’s core is primarily", ["iron", "oxygen", "carbon", "gold", "water"], "iron"),
        ("A thermometer measures", ["temperature", "pressure", "speed", "weight", "volume"], "temperature"),
        ("The process of liquid to gas is", ["evaporation", "freezing", "melting", "condensation", "sublimation"], "evaporation"),
        ("Oxygen is necessary for", ["respiration", "photosynthesis", "evaporation", "gravity", "magnetism"], "respiration"),
        ("The basic unit of life is the", ["cell", "atom", "molecule", "organ", "tissue"], "cell"),
        ("A barometer measures", ["pressure", "temperature", "speed", "humidity", "light"], "pressure"),
        ("The primary component of natural gas is", ["methane", "oxygen", "nitrogen", "carbon dioxide", "helium"], "methane"),
        ("Rust is formed by", ["oxidation", "reduction", "evaporation", "melting", "freezing"], "oxidation"),
        ("The Earth revolves around the", ["sun", "moon", "stars", "planets", "galaxy"], "sun"),
        ("A pulley is used to", ["lift", "cut", "push", "pull", "turn"], "lift"),
        ("The primary gas in the sun is", ["hydrogen", "oxygen", "nitrogen", "helium", "carbon"], "hydrogen"),
        ("Sound cannot travel through a", ["vacuum", "air", "water", "metal", "wood"], "vacuum"),
        ("The human body’s main energy source is", ["carbohydrates", "vitamins", "minerals", "water", "oxygen"], "carbohydrates"),
        ("The primary cause of seasons is Earth’s", ["tilt", "rotation", "orbit", "distance", "shape"], "tilt"),
        ("A base turns litmus paper", ["blue", "red", "green", "yellow", "white"], "blue"),
        ("The most abundant element in the universe is", ["hydrogen", "oxygen", "carbon", "nitrogen", "helium"], "hydrogen"),
        ("A magnet attracts", ["iron", "wood", "plastic", "glass", "water"], "iron"),
        ("The process of gas to liquid is", ["condensation", "evaporation", "freezing", "melting", "sublimation"], "condensation"),
        ("The Earth’s crust is mostly", ["oxygen", "iron", "carbon", "nitrogen", "silicon"], "oxygen"),
        ("A fossil is evidence of past", ["life", "rock", "water", "wind", "fire"], "life"),
        ("The speed of light is approximately", ["300,000 km/s", "300 km/s", "3,000 km/s", "30 km/s", "3 km/s"], "300,000 km/s"),
        ("The primary organ for digestion is the", ["stomach", "lungs", "heart", "brain", "liver"], "stomach"),
        ("A prism separates light into", ["colors", "sounds", "waves", "particles", "beams"], "colors"),
        ("The primary source of wind is", ["sun", "moon", "earth", "ocean", "stars"], "sun"),
        ("An insulator prevents the flow of", ["electricity", "light", "sound", "heat", "water"], "electricity"),
        ("The Earth’s rotation causes", ["day and night", "seasons", "tides", "wind", "rain"], "day and night"),
        ("The primary gas in Earth’s oceans is", ["none", "oxygen", "nitrogen", "hydrogen", "carbon dioxide"], "none"),
        ("A chemical reaction produces new", ["substances", "elements", "atoms", "cells", "ions"], "substances"),
        ("The primary source of earthquakes is", ["tectonic plates", "wind", "water", "sun", "moon"], "tectonic plates"),
        ("The human skeleton is made mostly of", ["bone", "muscle", "skin", "blood", "cartilage"], "bone")
    ]
    random.shuffle(facts)
    questions = [f"{q}\nOptions: {', '.join(opts)}" for q, opts, _ in facts]
    answers = [ans for _, _, ans in facts]
    return questions[:20], answers[:20], None