# questions/verbal.py
import random

def generate_verbal_analogies_questions():
    # Already hardcoded with 50 questions from previous response
    analogies = [
        ("Dog is to bark as cat is to", ["meow", "run", "eat", "sleep", "jump"], "meow"),
        ("Knife is to cut as pen is to", ["write", "draw", "stab", "erase", "point"], "write"),
        ("Hot is to cold as up is to", ["down", "side", "left", "right", "over"], "down"),
        ("Bird is to feather as fish is to", ["scale", "fin", "gill", "water", "tail"], "scale"),
        ("Pilot is to airplane as captain is to", ["ship", "car", "train", "bike", "horse"], "ship"),
        ("Water is to liquid as ice is to", ["solid", "gas", "vapor", "snow", "crystal"], "solid"),
        ("Book is to read as movie is to", ["watch", "write", "listen", "edit", "act"], "watch"),
        ("Day is to night as light is to", ["dark", "bright", "sun", "moon", "shadow"], "dark"),
        ("Wheel is to car as wing is to", ["plane", "bird", "rocket", "boat", "train"], "plane"),
        ("Teacher is to educate as doctor is to", ["heal", "build", "teach", "drive", "judge"], "heal"),
        ("Apple is to fruit as carrot is to", ["vegetable", "meat", "grain", "seed", "flower"], "vegetable"),
        ("Fast is to slow as tall is to", ["short", "high", "long", "wide", "big"], "short"),
        ("Engine is to car as propeller is to", ["airplane", "boat", "train", "bicycle", "truck"], "airplane"),
        ("Rain is to wet as sun is to", ["dry", "hot", "bright", "cold", "cloudy"], "dry"),
        ("Glove is to hand as sock is to", ["foot", "head", "arm", "leg", "neck"], "foot"),
        ("Hammer is to nail as screwdriver is to", ["screw", "bolt", "wood", "metal", "paint"], "screw"),
        ("Summer is to warm as winter is to", ["cold", "hot", "rainy", "windy", "dry"], "cold"),
        ("Eye is to see as ear is to", ["hear", "touch", "smell", "taste", "look"], "hear"),
        ("Tree is to forest as star is to", ["sky", "planet", "moon", "ocean", "field"], "sky"),
        ("Chef is to cook as painter is to", ["paint", "draw", "build", "sing", "write"], "paint"),
        ("Big is to small as heavy is to", ["light", "large", "tall", "short", "wide"], "light"),
        ("Clock is to time as thermometer is to", ["temperature", "speed", "distance", "weight", "height"], "temperature"),
        ("Fish is to swim as bird is to", ["fly", "run", "jump", "crawl", "sing"], "fly"),
        ("Road is to car as runway is to", ["plane", "train", "boat", "bike", "truck"], "plane"),
        ("Happy is to sad as success is to", ["failure", "joy", "effort", "win", "loss"], "failure"),
        ("Leaf is to tree as petal is to", ["flower", "stem", "root", "branch", "seed"], "flower"),
        ("Soldier is to army as sailor is to", ["navy", "air force", "school", "team", "crew"], "navy"),
        ("Salt is to salty as sugar is to", ["sweet", "sour", "bitter", "spicy", "bland"], "sweet"),
        ("Map is to location as calendar is to", ["date", "time", "place", "event", "season"], "date"),
        ("Candle is to wax as lamp is to", ["oil", "fire", "light", "glass", "wire"], "oil"),
        ("Shoe is to foot as helmet is to", ["head", "hand", "chest", "leg", "back"], "head"),
        ("Oven is to bake as stove is to", ["cook", "boil", "fry", "cool", "heat"], "cook"),
        ("Puppy is to dog as kitten is to", ["cat", "mouse", "rabbit", "bird", "fish"], "cat"),
        ("North is to south as east is to", ["west", "up", "down", "left", "right"], "west"),
        ("Window is to house as porthole is to", ["ship", "car", "plane", "train", "tent"], "ship"),
        ("Loud is to quiet as bright is to", ["dim", "dark", "loud", "soft", "clear"], "dim"),
        ("Key is to lock as password is to", ["code", "door", "safe", "phone", "gate"], "code"),
        ("River is to water as desert is to", ["sand", "rock", "wind", "heat", "dust"], "sand"),
        ("Judge is to courtroom as pilot is to", ["cockpit", "runway", "plane", "ship", "tower"], "cockpit"),
        ("Tire is to bicycle as sail is to", ["boat", "plane", "car", "kite", "train"], "boat"),
        ("Hard is to soft as rough is to", ["smooth", "tough", "flat", "sharp", "wet"], "smooth"),
        ("Doctor is to hospital as teacher is to", ["school", "office", "clinic", "library", "home"], "school"),
        ("Sky is to blue as grass is to", ["green", "brown", "yellow", "red", "white"], "green"),
        ("Fork is to eat as shovel is to", ["dig", "cut", "lift", "pour", "build"], "dig"),
        ("Minute is to hour as inch is to", ["foot", "yard", "mile", "meter", "second"], "foot"),
        ("Seed is to plant as egg is to", ["bird", "fish", "snake", "insect", "tree"], "bird"),
        ("Mountain is to ridge as ocean is to", ["wave", "trench", "current", "tide", "shore"], "wave"),
        ("Smile is to joy as frown is to", ["sadness", "anger", "fear", "surprise", "pain"], "sadness"),
        ("Ruler is to measure as compass is to", ["navigate", "draw", "cut", "point", "turn"], "navigate"),
        ("Sun is to day as moon is to", ["night", "star", "sky", "cloud", "dawn"], "night")
    ]
    random.shuffle(analogies)
    questions = [f"{q}\nOptions: {', '.join(opts)}" for q, opts, _ in analogies]
    answers = [ans for _, _, ans in analogies]
    return questions[:25], answers[:25], None

def generate_word_knowledge_questions():
    words = [
        ("Feline means", ["dog", "cat", "bird", "fish", "snake"], "cat"),
        ("Rapid means", ["slow", "fast", "calm", "steady", "quiet"], "fast"),
        ("Abate means", ["increase", "decrease", "start", "grow", "expand"], "decrease"),
        ("Benevolent means", ["kind", "cruel", "angry", "sad", "harsh"], "kind"),
        ("Cautious means", ["careful", "reckless", "bold", "quick", "lazy"], "careful"),
        ("Debris means", ["trash", "food", "water", "tools", "clothes"], "trash"),
        ("Eloquent means", ["fluent", "silent", "rude", "slow", "weak"], "fluent"),
        ("Fatigue means", ["tiredness", "energy", "speed", "strength", "hunger"], "tiredness"),
        ("Genuine means", ["real", "fake", "old", "new", "broken"], "real"),
        ("Hostile means", ["unfriendly", "kind", "happy", "calm", "peaceful"], "unfriendly"),
        ("Illuminate means", ["light", "darken", "hide", "cover", "dim"], "light"),
        ("Jovial means", ["cheerful", "sad", "angry", "tired", "shy"], "cheerful"),
        ("Keen means", ["sharp", "dull", "soft", "weak", "slow"], "sharp"),
        ("Lethargic means", ["lazy", "active", "fast", "strong", "alert"], "lazy"),
        ("Mundane means", ["ordinary", "exciting", "rare", "strange", "unique"], "ordinary"),
        ("Noxious means", ["harmful", "safe", "sweet", "pleasant", "clean"], "harmful"),
        ("Obscure means", ["hidden", "clear", "bright", "open", "simple"], "hidden"),
        ("Pensive means", ["thoughtful", "careless", "happy", "loud", "quick"], "thoughtful"),
        ("Querulous means", ["complaining", "quiet", "content", "helpful", "calm"], "complaining"),
        ("Robust means", ["strong", "weak", "small", "fragile", "soft"], "strong"),
        ("Sporadic means", ["irregular", "constant", "steady", "frequent", "daily"], "irregular"),
        ("Tactile means", ["touch", "sight", "sound", "taste", "smell"], "touch"),
        ("Unanimous means", ["agreed", "divided", "mixed", "opposed", "silent"], "agreed"),
        ("Vivid means", ["bright", "dull", "faint", "dark", "quiet"], "bright"),
        ("Wary means", ["cautious", "bold", "careless", "quick", "trusting"], "cautious"),
        ("Zealous means", ["eager", "lazy", "calm", "tired", "bored"], "eager"),
        ("Candid means", ["honest", "secretive", "rude", "quiet", "shy"], "honest"),
        ("Diligent means", ["hardworking", "lazy", "slow", "careless", "weak"], "hardworking"),
        ("Erratic means", ["unpredictable", "steady", "calm", "regular", "smooth"], "unpredictable"),
        ("Frugal means", ["thrifty", "wasteful", "rich", "generous", "poor"], "thrifty"),
        ("Grim means", ["serious", "happy", "light", "funny", "easy"], "serious"),
        ("Hasty means", ["quick", "slow", "careful", "steady", "planned"], "quick"),
        ("Inert means", ["still", "active", "moving", "fast", "strong"], "still"),
        ("Jargon means", ["slang", "poetry", "song", "story", "speech"], "slang"),
        ("Luminous means", ["bright", "dark", "dull", "hidden", "faint"], "bright"),
        ("Meager means", ["small", "large", "plenty", "full", "rich"], "small"),
        ("Nebulous means", ["vague", "clear", "sharp", "exact", "bright"], "vague"),
        ("Ominous means", ["threatening", "safe", "calm", "happy", "peaceful"], "threatening"),
        ("Pristine means", ["clean", "dirty", "old", "worn", "broken"], "clean"),
        ("Quaint means", ["charming", "ugly", "modern", "plain", "dull"], "charming"),
        ("Resilient means", ["adaptable", "rigid", "weak", "fragile", "stiff"], "adaptable"),
        ("Stagnant means", ["still", "flowing", "moving", "active", "fresh"], "still"),
        ("Tepid means", ["lukewarm", "hot", "cold", "boiling", "freezing"], "lukewarm"),
        ("Unruly means", ["wild", "calm", "orderly", "quiet", "tame"], "wild"),
        ("Vague means", ["unclear", "clear", "exact", "sharp", "precise"], "unclear"),
        ("Wane means", ["decrease", "increase", "grow", "rise", "expand"], "decrease"),
        ("Xenophobic means", ["fearful", "friendly", "open", "curious", "welcoming"], "fearful"),
        ("Yield means", ["produce", "destroy", "hide", "lose", "break"], "produce"),
        ("Zeal means", ["passion", "apathy", "calm", "fear", "doubt"], "passion"),
        ("Arid means", ["dry", "wet", "cold", "hot", "humid"], "dry"),
        ("Blatant means", ["obvious", "hidden", "subtle", "quiet", "secret"], "obvious")
    ]
    random.shuffle(words)
    questions = [f"{q}\nOptions: {', '.join(opts)}" for q, opts, _ in words]
    answers = [ans for _, _, ans in words]
    return questions[:25], answers[:25], None